// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_nNLCuytlnqeGgaQw4jg7t0EEidB7BK8',
    appId: '1:358443086601:web:26bffb6ea46531cbfb59d8',
    messagingSenderId: '358443086601',
    projectId: 'oxdo-firebase-29573',
    authDomain: 'oxdo-firebase-29573.firebaseapp.com',
    storageBucket: 'oxdo-firebase-29573.firebasestorage.app',
    measurementId: 'G-64EVP5V1W2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI2wmoCOzaPf-7EyfOzfMWCg28C-q9XnI',
    appId: '1:358443086601:android:2e125fdf1fece3c9fb59d8',
    messagingSenderId: '358443086601',
    projectId: 'oxdo-firebase-29573',
    storageBucket: 'oxdo-firebase-29573.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTeuX5-7Y5OE616w0b7wtcNkqT83XHvZg',
    appId: '1:358443086601:ios:7375bd753b8ccdb5fb59d8',
    messagingSenderId: '358443086601',
    projectId: 'oxdo-firebase-29573',
    storageBucket: 'oxdo-firebase-29573.firebasestorage.app',
    iosBundleId: 'com.example.oxdoMessage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTeuX5-7Y5OE616w0b7wtcNkqT83XHvZg',
    appId: '1:358443086601:ios:7375bd753b8ccdb5fb59d8',
    messagingSenderId: '358443086601',
    projectId: 'oxdo-firebase-29573',
    storageBucket: 'oxdo-firebase-29573.firebasestorage.app',
    iosBundleId: 'com.example.oxdoMessage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_nNLCuytlnqeGgaQw4jg7t0EEidB7BK8',
    appId: '1:358443086601:web:b712a0ac4ac09cc0fb59d8',
    messagingSenderId: '358443086601',
    projectId: 'oxdo-firebase-29573',
    authDomain: 'oxdo-firebase-29573.firebaseapp.com',
    storageBucket: 'oxdo-firebase-29573.firebasestorage.app',
    measurementId: 'G-CB637GQN1N',
  );
}
